# Do not use this file as example
# Check the README
- id: biz4a-checks-odoo-module
  name: Checks for py, csv and xml files of Odoo modules
  description: Multiple checks for Odoo modules
  entry: biz4a-checks-odoo-module
  args: []
  language: python
  types_or: ["csv", "python", "xml"]
  # TODO: Check if should consider uppercase extension
  files: \.(csv|xml)$|/\_\_(manifest|openerp)\_\_.py$
  # require_serial to evaluate the whole module in-one-shot to have full context about other xmlids and so on
  require_serial: true
- id: biz4a-checks-odoo-module-fixit
  name: Checks for py files of Odoo modules with fixit
  description: Multiple checks for Odoo modules with autofixes
  entry: biz4a-checks-odoo-module-fixit
  args: []
  language: python
  types_or: ["python"]
  files: \.py$
  # require_serial false to run parallels jobs faster
  require_serial: false
- id: biz4a-checks-po
  name: Checks for .po[t] files
  description: Multiple checks for PO files
  entry: biz4a-checks-po
  args: []
  language: python
  # Notice the "pofile" type does not consider "pot" files
  # The command "identify-cli file.pot"
  # returns "text"
  types_or: ["text"]
  files: \.(po|pot)$
  require_serial: false
